apiVersion: apps/v1
kind: Deployment
metadata:
  name: work-user-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: InternRFC-app-work-user
  template:
    metadata:
      labels:
        app: InternRFC-app-work-user
    spec:
      containers:
      - name: work-wser-container
        image: salmak22/rapportimage
        ports:
        - containerPort: 3000
